#!/bin/bash

#REMOVEME? YNH_APP_ARG_DOMAIN=$YNH_APP_NEW_DOMAIN
#REMOVEME? YNH_APP_ARG_PATH=$YNH_APP_NEW_PATH

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd service '$app'..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# MODIFY SETTINGS
#=================================================
ynh_script_progression "Modify $app config file..."

ynh_config_add --template="settings.py" --destination="$install_dir/settings.py"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
