#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status "$app" >/dev/null 2>&1; then
    yunohost service remove "$app"
fi

ynh_config_remove_logrotate

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_redis_remove_db "$redis_db"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
