#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chmod o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE THE POSTGRES DATABASE
#=================================================
ynh_script_progression "Restoring the Postgresql database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# PYTHON VIRTUALENV
#=================================================
ynh_script_progression "Update Python virtualenv..."

python3 -m venv --upgrade --without-pip "$install_dir/venv"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Digital signage system for high schools" --log="/var/log/$app/$app.log"

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/var/log/$app/"
chown -R "$app:" "/var/log/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Restoration completed for $app"
